name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  intl: ^0.20.2
  mockingjay: ^2.0.0
  shadcn_ui:
    git:
      url: https://github.com/nank1ro/flutter-shadcn-ui
  shimmer: ^3.0.0
  vector_graphics: any
dev_dependencies:
  build_runner: ^2.5.3
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    # - assets/icons/
    # - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansEthiopic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansEthiopic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansEthiopic-Regular.ttf
          weight: 400
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          weight: 400

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
