name: frappify
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_logger:
    path: ../../packages/app_logger
  app_ui:
    path: ../../packages/app_ui
  bloc: ^9.0.0
  country_flags: ^3.3.0
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  frappe_client:
    path: ../../packages/frappe_client
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hugeicons: ^0.0.11
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  introduction_screen: ^3.1.17
  path: ^1.9.1
  path_provider: ^2.1.5
  persistent_storage:
    path: ../../packages/persistent_storage
  provider: ^6.1.5
  responsive_framework: ^1.5.1
  secure_storage:
    path: ../../packages/secure_storage
  toastification: ^3.0.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: true
